In [1]:
import tensorflow as tf

D:\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
zero_tsr = tf.zeros([3, 4])

In [4]:
print(zero_tsr)

Tensor("zeros:0", shape=(3, 4), dtype=float32)


In [5]:
with tf.Session() as sess:
    print(sess.run(zero_tsr))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [2]:
ones_tsr = tf.ones([3, 4])
sess = tf.Session()
print(sess.run(ones_tsr))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
filled_str = tf.fill([3, 5], 8)
print(sess.run(filled_str))

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [9]:
constant_tsr = tf.constant([1, 2, 3])

In [10]:
print(sess.run(constant_tsr))

[1 2 3]


In [11]:
zeros_similar = tf.zeros_like(filled_str)

In [13]:
print(sess.run(zeros_similar))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [14]:
ones_similar = tf.ones_like(filled_str)
print(sess.run(ones_similar))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [17]:
liner_tsr = tf.linspace(start=0.0, stop=1.0, num=3)
print(sess.run(liner_tsr))

[0.  0.5 1. ]


In [18]:
integer_seq_tsr = tf.range(start=6, limit=15, delta=3)
print(sess.run(integer_seq_tsr))

[ 6  9 12]


In [19]:
randunif_tsr = tf.random_uniform([3, 4], minval=0, maxval=1)
print(sess.run(randunif_tsr))

[[0.09133184 0.7605548  0.55111146 0.11887336]
 [0.65355015 0.60788214 0.9826534  0.52251315]
 [0.2067734  0.01081359 0.06674957 0.6516955 ]]


In [20]:
random_tsr = tf.random_normal([4, 6], mean=0.0, stddev=1.0)

In [21]:
print(sess.run(random_tsr))

[[-0.5583595  -0.5464583  -0.6305885  -0.98019695 -1.6994107  -0.78902245]
 [ 1.7786314  -2.3182425  -0.43818867  0.337098   -0.9131908   0.4080881 ]
 [ 0.04024762  0.70316726  0.8073331  -0.2760188  -0.17139664  0.19664106]
 [ 1.0349767   2.554274   -0.34155247  0.05398611  0.43061793 -0.5049153 ]]


In [24]:
runcnorm_tsr = tf.truncated_normal([4, 6], mean=0.0, stddev=0.5)
print(sess.run(runcnorm_tsr))


[[ 0.493275    0.19145721 -0.09413868  0.6801738  -0.7865269   0.95233124]
 [-0.7116119   0.09170453  0.23080021 -0.35808074 -0.03871695  0.06458732]
 [-0.33927402 -0.7794861  -0.81758493 -0.42337865 -0.7198976   0.07546812]
 [-0.66801244  0.94304174 -0.6616636   0.64272034  0.10010324  0.21272375]]


In [25]:
shuffled_output = tf.random_shuffle(runcnorm_tsr)
print(sess.run(shuffled_output))

[[ 0.19487596  0.11140264 -0.5998873  -0.3335906  -0.4349075   0.06493827]
 [-0.34026518 -0.6983608   0.12139051  0.262019   -0.74909997 -0.48360294]
 [ 0.32367584  0.29537684  0.40478525 -0.5350276  -0.05509219 -0.29202276]
 [-0.346764   -0.7460656  -0.5040702   0.56750655  0.39600596  0.29743114]]


In [27]:
cropped_output = tf.random_crop(runcnorm_tsr, [2, 3])
print(sess.run(cropped_output))

[[-0.7016905  -0.8148107  -0.68533754]
 [ 0.11441954 -0.3972594  -0.39595532]]
[[ 0.33274695  0.12775631  0.40301266 -0.27433497  0.04358308  0.13154833]
 [-0.26672214  0.43141505 -0.42387488 -0.6928038   0.21767583 -0.53229314]
 [-0.57680017 -0.03041673  0.03673094 -0.15290093 -0.23118593  0.15353867]
 [-0.57995707 -0.60914344  0.6209325  -0.5490348   0.16109169  0.07573172]]


In [3]:
import numpy as np
identity_matrix = tf.diag([1.0, 1.0, 1.0])
D = tf.convert_to_tensor(np.array([[1.0, 2.0, 3.0], [-3.0, -7.0, -1.0], [0.0, 5.0, -2.0]]))
print(sess.run(identity_matrix))
print(sess.run(D))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]


In [4]:
print(sess.run(tf.matrix_determinant(D)))

-37.99999999999999


In [5]:
print(sess.run(tf.matrix_inverse(D)))

[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]]


In [6]:
print(sess.run(tf.cholesky(identity_matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
print(sess.run(tf.self_adjoint_eig(D)))

(array([-10.65907521,  -0.22750691,   2.88658212]), array([[ 0.21749542,  0.63250104, -0.74339638],
       [ 0.84526515,  0.2587998 ,  0.46749277],
       [-0.4880805 ,  0.73004459,  0.47834331]]))


In [9]:
print(sess.run(tf.cholesky(identity_matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
print(sess.run(tf.truediv(3, 4)))

0.75


In [12]:
print(sess.run(tf.cross([1.0, 0.0, 0.0], [0.0, 1.0 , 0.0])))

[0. 0. 1.]


In [13]:
print(sess.run(tf.multiply([1.0, 0.0, 0.0], [0.0, 1.0 , 0.0])))

[0. 0. 0.]


In [17]:
print(sess.run(tf.multiply([[0.0, 1.0 , 0.0]], [[1.0], [0.0], [0.0]])))

[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
print(sess.run(tf.matmul([[0.0, 1.0 , 0.0]], [[1.0], [0.0], [0.0]])))

[[0.]]


In [19]:
print(sess.run(tf.sin(3.1416/4.0)))

0.7071081


In [20]:
print(sess.run(tf.cos(3.1416/4.0)))

0.7071055


In [21]:
print(sess.run(tf.div(tf.sin(3.1416/4.0), tf.cos(3.1416/4.0))))

1.0000036


In [23]:
print(sess.run(tf.nn.relu([-3, 3, 10])))

[ 0  3 10]


In [28]:
print(sess.run(tf.nn.relu6([-3, 3, 10])))

[0 3 6]


In [29]:
print(sess.run(tf.nn.sigmoid([-1.0, 0.0, 1.0])))

[0.26894143 0.5        0.7310586 ]


In [33]:
print(sess.run(tf.nn.tanh([-100.0, 0.0, 1.0])))

[-1.         0.         0.7615942]


In [34]:
print(sess.run(tf.nn.softsign([-1.0, 0.0, 1.0])))

[-0.5  0.   0.5]


In [37]:
print(sess.run(tf.nn.softplus([-1.0, 0.0, 1.0])))

[0.31326166 0.6931472  1.3132616 ]


In [38]:
print(sess.run(tf.nn.elu([-1.0, 0.0, 1.0])))

[-0.63212055  0.          1.        ]


In [39]:
from sklearn import datasets
iris = datasets.load_iris()

In [40]:
print(len(iris.data))

150


In [41]:
iris.data.shape

(150, 4)

In [42]:
iris.target.shape

(150,)

In [43]:
iris.data[0]

array([5.1, 3.5, 1.4, 0.2])

In [45]:
iris.target[1]

0